ECHO Recompiling Hawk's Machinery...
runtime\bin\python\python_mcp runtime\recompile.py %*
ECHO Copying over Hawk's Machinery sources...
runtime\bin\python\python_mcp runtime\getchangedsrc.py %*
ECHO Reobfuscating Hawk's Machinery...
runtime\bin\python\python_mcp runtime\reobfuscate.py %*
ECHO Done!
PAUSE